spring:
  datasource:
    driver_class_name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.0.194:3306/database_v2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: a15924786020
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: [file:D:\Smartheal\service\static\]
#  web:
#    resources:
#      static-locations: D:\Smartheal\service\static\


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  file:
    path: C:\Users\LANGLANG\Desktop\server


server:
  port: 8888

diet plan:
  pythonExe: E:\Anaconda3\envs\sklearn\python.exe
  recipeScript: D:\Smartheal\后端\harmony-osapp-server\src\main\java\com\example\test\python\recipe_generation.py
  dietScript: D:\Smartheal\后端\harmony-osapp-server\src\main\java\com\example\test\python\read_data.py

config:
  env: dev
  imagPath: D:\Smartheal\service\static\images\

register-config:
  accessKeyId: LTAI5tP8KFown9kHhpbSmVRD
  accessKeySecret: c2ZVcjqmDY5iUKvwzNQj3ZPiNUoUoc
  signName: 阿里云短信测试
  setTemplateCode: SMS_154950909
