spring:
  datasource:
    driver_class_name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx/database_v2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: sdf
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: [file:D:\Smartheal\service\static\]
#  web:
#    resources:
#      static-locations: D:\Smartheal\service\static\


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.example.test.typehandler



logging:
  file:
    path: C:\Users\LANGLANG\Desktop\server


server:
  port: 8888
  servlet:
    session:
      timeout: 1209600 # 2周

diet plan:
  pythonExe: E:\Anaconda3\envs\sklearn\python.exe
  recipeScript: I:\Smartheal\model\recipe\main.py
  dietScript: D:\Smartheal\后端\harmony-osapp-server\src\main\java\com\example\test\python\read_data.py

config:
  env: dev
  imgPath: I:\Smartheal\service\static\images\
  recipeImage: D:\images\
  apkPath: D:\java\tmp\ # 需要加末尾斜杠
  apkBaseUrl: http://xxxxx/apk/ # 需要加末尾斜杠



register-config:
  accessKeyId: aaa
  accessKeySecret: aaa
  signName: 阿里云短信测试
  setTemplateCode: aaa
